name: Publish Package

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - name: Install
        run: |
          yarn
      - name: Build
        run: |
          yarn build
      - name: Publish
        run: |
          cd dist
          npm publish --access public
